# Generated by Django 2.2.1 on 2019-05-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='username',
            new_name='user',
        ),
    ]
